### ISSUE TITLE
The view files in the solution are missing

### ISSUE THREAD

**Issue by jonbf** [learn-co-students/has-many-through-forms-rails-labs-v-000#250]
For instance, https://github.com/learn-co-students/has-many-through-forms-rails-labs-v-000/blob/solution/app/views/posts/show.html.erb is blank

**Comment by drakeltheryuujin** [comment]
Hi there,

Issues with a lesson in the curriculum should be opened on the appropriate repository in `learn-co-curriculum`.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. Thanks for contributing! 💙
