### ISSUE TITLE
No soultion

### ISSUE THREAD

**Issue by johanesteves** [learn-co-students/has-many-through-forms-rails-labs-v-000#468]
There are no solutions for this lab. This was a tough one for me, would love to compare my results.

**Comment by TheInvalidNonce** [comment]
+1, this lab was already confusing enough with the vague directions in the show page. And not knowing what the best solution is, makes it harder to takeaway much from this lab.

**Comment by byojelly** [comment]
+2 No solution, please update

**Comment by avelineamour** [comment]
+3 -- No solution.

**Comment by atxrenegade** [comment]
+4 --no solution for this lab or the previous lab

**Comment by meg-gutshall** [comment]
Since there's still no solution for this lab, you're all welcome to take a look at mine (for learning purposes, please no copy/pasting). I'm not saying it's the best, but it works! https://github.com/meg-gutshall/has-many-through-forms-rails-labs-v-000

**Comment by drakeltheryuujin** [comment]
Hi there,

Issues with a lesson in the curriculum should be opened on the appropriate repository in `learn-co-curriculum`.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. Thanks for contributing! 💙
