### ISSUE TITLE
Unclear tests for Post NEW section

### ISSUE THREAD

**Issue by lisaychuang** [learn-co-students/has-many-through-forms-rails-labs-v-000#500]
In the current test suite, there are 4 tests under the Post NEW section:

```
Posts
  new
    can create a post without a new category
    can create a post with a previously created category
    can create a post with a brand new category
    can create a post with a brand new category and an existing category
```

I was stuck on tests 2,3,4 for the longest time, and couldn't figure out why my tests were failing.

After 30mins and looking at another student's solution - I realized these 3 tests were checking for categories to be displayed on the **posts/show.html.erb**...

In the original instructions, the section on Post SHOW page states:

**Create a posts#show page to display the following:**
1. The title and content of the post.
2. All of the comments associated with the post.
3. A list of all the unique users who have commented on the post. A user's name should only show up once in this section, even if they've commented multiple times.
4. A form to add a new comment. The form should have a drop-down menu to select a user (we'll change this in future lessons to automatically associate the comment with a logged-in user). We should also be able to create a new user here and automatically associate it with the post.

The instructions did not ask for **categories** to be displayed on the #show page, so it was very confusing that tests in the **posts#new** section was dependent on the #show page...!

Please update the instructions by:
- Changing the test to check for @post.categories_id directly
- Move the 3 confusing tests to post#show section
- Include categories for post#show page instructions 

Thanks,
Lisa

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
