### ISSUE TITLE
Unclear how to associate post with new comment

### ISSUE THREAD

**Issue by Madeline-Stark** [learn-co-students/has-many-through-forms-rails-labs-v-000#918]
Hi,

I think it would be helpful to have a little more direction as to how to associate a new comment in the show page with that post. There are no instructions in any of the read mes that you have to use a hidden field in your comment form like so: <%= f.hidden_field :post_id, value: @post.id %>

Thanks,

Madeline

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
